#pragma once

#include <cstdint>
#include <map>
#include <memory>
#include <string>
#include <unordered_map>
#include <utility>
#include <vector>

#include "anonymouslabel.h"
#include "options.h"
#include "ruletype.h"
#include "sourceManager.h"
#include "statement.h"
#include "symboltable.h"

/**
 * @file multipassassembler.h
 * @author Paul Baxter
 */

/**
 * @class MultiPassAssembler
 * @brief Orchestrates multi-pass symbol resolution, AST transformations, and code generation.
 * @author Paul Baxter
 *
 * The `MultiPassAssembler` class processes an Abstract Syntax Tree (AST) composed of 
 * `Statement` nodes across multiple iterative passes. It handles label mapping, zero-page 
 * vs. absolute instruction sizing, variable mutation, control flow directives (`if`, `loop`), 
 * and automatic branch trampoline ("island") generation when relative branch limits are exceeded.
 */
class MultiPassAssembler {
private:
    SourceManager& src_mgr; ///< Source manager for files and diagnostics.
    Options options;        ///< Command-line options and assembler configuration.

    /**
     * @enum LoopControlKind
     * @brief Denotes control flow state mutations during loop expansion.
     */
    enum LoopControlKind {
        normal,        ///< Standard sequential execution state.
        break_loop,    ///< Break condition encountered; terminates active loop context.
        continue_loop  ///< Continue condition encountered; skips remaining statements in loop body.
    };

    int loopControl = LoopControlKind::normal; ///< Current loop execution control flow state.
    SymbolTable symbols_{"SYM", src_mgr};      ///< Table storing fixed labels and symbolic constants.
    SymbolTable vars_{"VAR", src_mgr};         ///< Table storing mutable assembly variables.
    
    bool changed = false;      ///< Indicates if any symbol or PC value mutated during the active pass.
    bool wait_stable = false; ///< Delay flag ensuring state consistency before final code emission.
    bool stable = false;       ///< Indicates that symbol addresses have fully converged across passes.
    uint16_t start_pc_ = 0;    ///< Initial program counter value set prior to assembly.
    int64_t loop_level = 0;    /// Nested loop level.
    /**
     * @brief Maps anonymous label scopes and statement indices to global anonymous IDs.
     * Key: std::pair<int scope_id, size_t statement_index>
     * Value: Resolved unique anonymous label sequence identifier.
     */
    std::map<std::pair<int, size_t>, size_t> anon_idmap;

    /**
     * @brief Formats an instruction operand into an assembly listing string.
     * @param mode Addressing mode rule (`RULE_TYPE`).
     * @param val Evaluated numeric operand value.
     * @param val2 Evaluated numeric operand value for ZeroPageRelative.
     * @return Formatted operand text representation.
     */
    std::string FormatOperand(RULE_TYPE mode, int64_t val, int64_t val2);

    /**
     * @brief Calculates instruction byte size based on its addressing mode.
     * @param mode Addressing mode rule (`RULE_TYPE`).
     * @return Memory allocation size in bytes (1, 2, or 3).
     */
    size_t GetInstructionSize(RULE_TYPE mode);

    std::string parent_scope = "GLOBAL_"; ///< Prefix for active local label scope.
    bool load_address_set = false;        ///< Tracks whether a `.org` directive set the initial load address.
    size_t pass = 1;                    ///< Active resolution pass counter.
    size_t max_passes = 10;             ///< Maximum convergence pass threshold prior to throwing an error.
    int island_counter = 0;             ///< Sequence index for generating unique branch trampoline (`@__island`) labels.

    /**
     * @brief Map of complementary 6502 branch opcodes used for branch relaxation.
     */
    const std::unordered_map<std::string, std::string> inverted_branches = {
        {"bne", "beq"}, {"beq", "bne"},
        {"bcc", "bcs"}, {"bcs", "bcc"},
        {"bvc", "bvs"}, {"bvs", "bvc"},
        {"bmi", "bpl"}, {"bpl", "bmi"}
    };

public:
    uint16_t load_address = 0;          ///< Target starting address in memory where the binary payload loads.
    uint16_t pc = 0;                   ///< Current program counter during AST traversal.
    std::vector<uint8_t> binary_output; ///< Generated byte payload emitted during the final assembly pass.
    std::string listing_file;          ///< Assembled output listing text stream.

    /**
     * @brief Exports the symbols in the symbol table.
     */
    [[nodiscard]] std::string ExportSymbols() {
        return symbols_.Export();
    }

    /**
     * @brief Exports cross-reference symbol usage details.
     */
    [[nodiscard]] std::string ExrefSymbols() const {
        return symbols_.XRef();
    }

    /**
     * @brief Constructs a new MultiPassAssembler object with developer configuration options.
     * @param opts Assembly options specifying start address, defines, and debug flags.
     * @param src Reference to SourceManager for diagnostic location mapping.
     */
    explicit MultiPassAssembler(Options opts, SourceManager& src)
        : src_mgr(src), options(std::move(opts)), start_pc_(options.start_addr) {}

    /**
     * @brief Drives multi-pass symbol resolution and controls final binary emission.
     *
     * Iteratively invokes `ResolutionPass` over the provided AST statements until addresses,
     * branches, and variables converge, or until `max_passes` is hit. Executes `EmitFinalPass` upon convergence.
     *
     * @param[in,out] statements AST statement stream to process.
     *
     * @throws std::runtime_error If symbol resolution fails to converge within `max_passes`.
     */
    void Assemble(std::vector<std::unique_ptr<Statement>>& statements);

private:
    /**
     * @brief Processes a single AST statement during a symbol resolution pass.
     *
     * Evaluates statement nodes, updates local symbol tables, optimizes addressing modes (Zero Page vs. Absolute),
     * unrolls control blocks (`if`/`loop`), and performs branch island insertions when branch displacements exceed relative limits.
     *
     * @param[in]     statements Original input statement vector for current pass.
     * @param[in,out] new_statements Transformed statement vector output for active pass state.
     * @param[in,out] st_index Reference to current statement index in `statements`.
     * @param[in,out] anonymous_labels List of tracking references for anonymous labels.
     */
    void ProcessStatement(std::vector<std::unique_ptr<Statement>>& statements, 
                          std::vector<std::unique_ptr<Statement>>& new_statements, 
                          size_t& st_index, 
                          std::vector<AnonymousLabel>& anonymous_labels);

    /**
     * @brief Executes a single top-to-bottom pass over all AST statements.
     * @param[in,out] statements Statement AST vector to process.
     * @param[in,out] anonymous_labels Tracked anonymous label sequence.
     * @return `true` if any symbol address, variable value, or instruction size mutated during the pass; `false` if converged.
     */
    bool ResolutionPass(std::vector<std::unique_ptr<Statement>>& statements, 
                        std::vector<AnonymousLabel>& anonymous_labels);

    /**
     * @brief Generates executable machine code and outputs listing details during the terminal pass.
     * @param[in] statements Fully-resolved AST statements vector.
     * @param[in] anonymous_labels Fully-resolved anonymous label definitions.
     */
    void EmitFinalPass(const std::vector<std::unique_ptr<Statement>>& statements, 
                       const std::vector<AnonymousLabel>& anonymous_labels);
};
