name: CMake on multiple platforms

on:
  push:
    branches: ["main"]

  pull_request:
    branches: ["main"]

  workflow_dispatch:

jobs:
  build:
    name: ${{ matrix.name }}
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false

      matrix:
        include:
          - name: Ubuntu GCC
            os: ubuntu-latest
            c_compiler: gcc
            cpp_compiler: g++

          - name: Ubuntu Clang
            os: ubuntu-latest
            c_compiler: clang
            cpp_compiler: clang++

          - name: Windows MSVC
            os: windows-latest
            c_compiler: cl
            cpp_compiler: cl

          - name: macOS Clang
            os: macos-latest
            c_compiler: clang
            cpp_compiler: clang++

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Configure CMake
        run: >
          cmake -B build
          -DCMAKE_CXX_COMPILER=${{ matrix.cpp_compiler }}
          -DCMAKE_C_COMPILER=${{ matrix.c_compiler }}
          -DCMAKE_BUILD_TYPE=Release
          -S .

      - name: Build
        run: cmake --build build --config Release
